version: '3'

volumes:
  postgres_data:
      driver: local

services:
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"

  viewer:
    build: ./OHIFViewer
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/ohif
    extra_hosts:
      - "pacsIP:192.168.0.5"
    volumes:
      - /opt/docker/ohif-viewer/app.json:/app/app.json
      - ./OHIFViewer:/app

  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      image: jboss/keycloak
      environment: 
        POSTGRES_ADDR: postgres
        POSTGRES_DATABASE: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it. 
        #JDBC_PARAMS: "ssl=true"
      ports:
        - 8080:8080
      depends_on:
        - postgres
  orthanc:
    image: jodogne/orthanc-plugins
    ports:
      - 4242:4242
      - 8042:8042